# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_name(object):
    def setupUi(self, name):
        name.setObjectName("name")
        name.resize(328, 356)
        self.verticalLayout = QtWidgets.QVBoxLayout(name)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(name)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(name)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CE = QtWidgets.QPushButton(name)
        self.CE.setMinimumSize(QtCore.QSize(60, 60))
        self.CE.setMaximumSize(QtCore.QSize(60, 60))
        self.CE.setObjectName("CE")
        self.gridLayout.addWidget(self.CE, 0, 3, 1, 1)
        self.Op_div = QtWidgets.QPushButton(name)
        self.Op_div.setMinimumSize(QtCore.QSize(60, 60))
        self.Op_div.setMaximumSize(QtCore.QSize(60, 60))
        self.Op_div.setObjectName("Op_div")
        self.gridLayout.addWidget(self.Op_div, 2, 3, 1, 1)
        self.Num_6 = QtWidgets.QPushButton(name)
        self.Num_6.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_6.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_6.setObjectName("Num_6")
        self.gridLayout.addWidget(self.Num_6, 1, 2, 1, 1)
        self.Num_8 = QtWidgets.QPushButton(name)
        self.Num_8.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_8.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_8.setObjectName("Num_8")
        self.gridLayout.addWidget(self.Num_8, 0, 1, 1, 1)
        self.Num_1 = QtWidgets.QPushButton(name)
        self.Num_1.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_1.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_1.setObjectName("Num_1")
        self.gridLayout.addWidget(self.Num_1, 2, 0, 1, 1)
        self.Op_equal = QtWidgets.QPushButton(name)
        self.Op_equal.setMinimumSize(QtCore.QSize(60, 60))
        self.Op_equal.setMaximumSize(QtCore.QSize(60, 60))
        self.Op_equal.setObjectName("Op_equal")
        self.gridLayout.addWidget(self.Op_equal, 3, 3, 1, 1)
        self.Num_9 = QtWidgets.QPushButton(name)
        self.Num_9.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_9.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_9.setObjectName("Num_9")
        self.gridLayout.addWidget(self.Num_9, 0, 2, 1, 1)
        self.Op_minus = QtWidgets.QPushButton(name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Op_minus.sizePolicy().hasHeightForWidth())
        self.Op_minus.setSizePolicy(sizePolicy)
        self.Op_minus.setMinimumSize(QtCore.QSize(60, 60))
        self.Op_minus.setMaximumSize(QtCore.QSize(60, 60))
        self.Op_minus.setObjectName("Op_minus")
        self.gridLayout.addWidget(self.Op_minus, 3, 2, 1, 1)
        self.Num_7 = QtWidgets.QPushButton(name)
        self.Num_7.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_7.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_7.setObjectName("Num_7")
        self.gridLayout.addWidget(self.Num_7, 0, 0, 1, 1)
        self.Num_4 = QtWidgets.QPushButton(name)
        self.Num_4.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_4.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_4.setObjectName("Num_4")
        self.gridLayout.addWidget(self.Num_4, 1, 0, 1, 1)
        self.Num_3 = QtWidgets.QPushButton(name)
        self.Num_3.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_3.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_3.setObjectName("Num_3")
        self.gridLayout.addWidget(self.Num_3, 2, 2, 1, 1)
        self.Num_5 = QtWidgets.QPushButton(name)
        self.Num_5.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_5.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_5.setObjectName("Num_5")
        self.gridLayout.addWidget(self.Num_5, 1, 1, 1, 1)
        self.Num_0 = QtWidgets.QPushButton(name)
        self.Num_0.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_0.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_0.setObjectName("Num_0")
        self.gridLayout.addWidget(self.Num_0, 3, 1, 1, 1)
        self.Num_2 = QtWidgets.QPushButton(name)
        self.Num_2.setMinimumSize(QtCore.QSize(60, 60))
        self.Num_2.setMaximumSize(QtCore.QSize(60, 60))
        self.Num_2.setObjectName("Num_2")
        self.gridLayout.addWidget(self.Num_2, 2, 1, 1, 1)
        self.Op_multiply = QtWidgets.QPushButton(name)
        self.Op_multiply.setMinimumSize(QtCore.QSize(60, 60))
        self.Op_multiply.setMaximumSize(QtCore.QSize(60, 60))
        self.Op_multiply.setObjectName("Op_multiply")
        self.gridLayout.addWidget(self.Op_multiply, 1, 3, 1, 1)
        self.Op_plus = QtWidgets.QPushButton(name)
        self.Op_plus.setMinimumSize(QtCore.QSize(60, 60))
        self.Op_plus.setMaximumSize(QtCore.QSize(60, 60))
        self.Op_plus.setObjectName("Op_plus")
        self.gridLayout.addWidget(self.Op_plus, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(name)
        QtCore.QMetaObject.connectSlotsByName(name)

    def retranslateUi(self, name):
        _translate = QtCore.QCoreApplication.translate
        name.setWindowTitle(_translate("name", "简易整数计算器-测试版"))
        self.label.setText(_translate("name", "计算器"))
        self.CE.setText(_translate("name", "CE"))
        self.Op_div.setText(_translate("name", "/"))
        self.Num_6.setText(_translate("name", "6"))
        self.Num_8.setText(_translate("name", "8"))
        self.Num_1.setText(_translate("name", "1"))
        self.Op_equal.setText(_translate("name", "="))
        self.Num_9.setText(_translate("name", "9"))
        self.Op_minus.setText(_translate("name", "-"))
        self.Num_7.setText(_translate("name", "7"))
        self.Num_4.setText(_translate("name", "4"))
        self.Num_3.setText(_translate("name", "3"))
        self.Num_5.setText(_translate("name", "5"))
        self.Num_0.setText(_translate("name", "0"))
        self.Num_2.setText(_translate("name", "2"))
        self.Op_multiply.setText(_translate("name", "*"))
        self.Op_plus.setText(_translate("name", "+"))
